name: "Domo WEB"
version: "2026.08.28"
slug: "domo-web-cfm"
description: "Apache con soporte para MSSQL"
url: "https://github.com/carferrer/domo-web-cfm"
image: "ghcr.io/carferrer/domo-web-cfm"
image_tag: "latest"
arch:
  - aarch64
  - amd64
map:
  - "addon_config:rw" #dentro del addo en /config y es persistente y accesible con samba
  - "ssl:ro"
schema:
  url: "str?"
  ssl_cert: "str?"
  ssl_key: "str?"
  log_level: "list(trace|debug|info|notice|warning|error|fatal|critical)?"
options:
  url: null
  ssl_cert: null
  ssl_key: null
  log_level: "warning"
ports:
  460/tcp: 460        # Puerto interno 460 fijo. El usuario cambia el externo en la pestaña Red.
ports_description:
  460/tcp: "Puerto externo de acceso para Domo WEB"
