name: "Domo WEB"
version: "2026.08.25"
slug: "domo-web-cfm"
description: "Apache con soporte para MSSQL"
url: "https://github.com/carferrer/domo-web-cfm"
image: "ghcr.io/carferrer/domo-web-cfm"
image_tag: "latest"
arch:
  - aarch64
  - amd64
map:
  - "addon_config:rw"
  - "ssl:ro"
schema:
  url: "str?"
  ssl_cert: "str?"
  ssl_key: "str?"
options:
  url: null
  ssl_cert: null
  ssl_key: null
ports:
  460/tcp: 460        # Puerto interno 460 fijo. El usuario cambia el externo en la pestaña Red.
ports_description:
  460/tcp: "Puerto externo de acceso para Domo WEB"
logger:
  default: warning
  logs:
    - trace
    - debug
    - info
    - notice
    - warning
    - error
    - fatal
    - critical
